StorageBodySize=100
StorageEngineSize=100
StorageAccessoriesSize=100
StorageAutoSize=100
AccessoriesSuppliers=5
Workers=10
LogSale=true
BodySupplyDelay=500
EngineDelay=700
AccessoriesDelay=200
Dealers=20
DealersDelay=1000