
StorageBodySize=100
StorageEngineSize=100
StorageAccessoriesSize=100
StorageAutoSize=100

BodySupplyDelay=500
EngineDelay=700
AccessoriesDelay=200

#EngineSupplier ? BodySupplier ??-??????
AccessoriesSuppliers=5
Workers=10
Dealers=20

DealersDelay=1000

LogSale=true

minCountAutoInStorage=50