StorageBodySize=100
StorageMotorSize=100
StorageAccessorySize=100
StorageAutoSize=100
AccessorySuppliers=5
Workers=10
Dealers=20
LogSale=true
BodySupplyDelay=500
MotorSupplyDelay=700
AccessorySupplyDelay=200
DealerDelay=1000